LABEL maintainer="jinjie" \
      description="Image used for running Cypress testing framework"
FROM cypress/browsers:latest
RUN npm i cypress -g
RUN npm install mysql -g
RUN npm install mocha -g
RUN npm install mochawesome -g
