#!/bin/sh
VERSION_CHROME="$(google-chrome --version | cut -d ' ' -f 3)";
printf "chrome:${VERSION_CHROME}\n";
VERSION_FIREFOX="$(firefox --version | cut -d ' ' -f 3)";
printf "firefox:${VERSION_FIREFOX}\n";
VERSION_K6="$(ls /root/.cache/ms-k6)"
printf "k6:${VERSION_K6}\n";