#!/bin/sh

VERSION_CHROMEDRIVER="$(chromedriver --version | cut -f 2 -d ' ')";
VERSION_CHROME="$(chrome --version | cut -f 3 -d ' ')";
VERSION_PYTHON="$(python --version 2>&1 | awk '{print $2}')";

printf "chromedriver:${VERSION_CHROMEDRIVER}\n";
printf "chrome:${VERSION_CHROME}\n";
printf "python:${VERSION_PYTHON}\n";