#!/bin/sh
VERSION_ATLANTIS=$(atlantis version | cut -f 2 -d ' ');
VERSION_TERRAGRUNT="$(terragrunt --version | cut -f 3 -d ' ' | cut -f 2 -d 'v')";
VERSION_TERRAFORM="$(terraform --version | cut -f 2 -d ' ' | cut -f 2 -d 'v')";
printf "atlantis:${VERSION_ATLANTIS}\n";
printf "terragrunt:${VERSION_TERRAGRUNT}\n";
printf "terraform:${VERSION_TERRAFORM}\n";